name: CI Pipeline

on: [pull_request, push]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Compile a universal OpenMP
      run: brew reinstall --build-from-source --formula ./.github/workflows/libomp.rb
      if: runner.os == 'macOS'

    - name: Configure and Build Project
      uses: threeal/cmake-action@main
      with:
        source-dir: simulator
        build-dir: simulator/build
